### ISSUE TITLE
[Request] Embed folders

### ISSUE THREAD

**Issue by AustinEast** [deepnight/redistHelper#2]
Hey, got a feature request! It would be super convenient to be able to embed whole folders along with individual files.

**Comment by deepnight** [comment]
It should be supported in latest commit :) You may switch your haxelib to the git repo:

``haxelib git redistHelper https://github.com/deepnight/redistHelper.git``

**Comment by deepnight** [comment]
Added in 0.4.3 release: https://github.com/deepnight/redistHelper/releases/tag/0.4.3
