### ISSUE TITLE
Add Comments Support

### ISSUE THREAD

**Issue by snsvrno** [deepnight/redistHelper#7]
I just updated my project hxmls with comments, and it looks like **resdistHelper** doesn't like that.

Not sure if comments are an approved feature of hxml, but my syntax highlighter (vscode) shows it as a comment and haxe / haxelib doesn't have any complaints about it.

**Example hxml file** (_I know not the most complex file, but comments would come in handy_)
```
# hl.dx.hxml
#
# direct x hashlink (win)

hxml/hl.hxml
-lib hldx
```

**Output**
```
Parsing hxml/hl.dx.hxml...
Called from ? line 1
Called from Main.hx line 189
Called from Main.hx line 536
Called from Main.hx line 532
Called from C:\projects\haxetools\haxe\std/neko/_std/sys/io/File.hx line 49
Uncaught exception - [file_open,# hl.dx.hxml]
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command haxelib run redistHelper hxml/hl.dx.hxml hxml/hl.sdl.hxml hxml/js.hxml -zip -hl32 -o bin/dist" terminated with exit code: 1.
```

**An Asside**
The error says its called from `C:\projects\haxetools\haxe\std/neko/_std/sys/io/File.hx line 49` but that isn't my filesystem, that must be yours? My haxe is located in `C:\HaxeToolkit\haxe\std\neko\_std\sys\io\File.hx`

**Comment by deepnight** [comment]
Oh right :) I'll fix that.
